import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Lato, Poppins } from "next/font/google";
import "./globals.css";

import { ToastContainer } from 'react-toastify';






import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "700"],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  style={{
      '--font-poppins': poppins.style.fontFamily,
      '--font-roboto':roboto.style.fontFamily,
      '--font-lato':lato.style.fontFamily
    } as React.CSSProperties}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${lato.variable} ${poppins.variable} antialiased`}
        
      >
        {children}

      
<ToastContainer />



      </body>
    </html>
  );
}
